### ISSUE TITLE
Uncaught Error: Image given has not completed loading

### ISSUE THREAD

**Issue by DragonCat4012** [AKORA-Studios/DiscordWelcomeCard#63]
```
client.on("messageCreate", async message => {
    console.log("A")

    if(message.author.id == "586905336850677760"){
            // const channel = await message.member.guild.channels.fetch("1054891541962956830");
            const image = await drawCard({
              theme: "circuit",
              text: {
                title: "Welcome to British Island Life,",
                text: `tag\n\nMember Count: 12`,
                color: `#88f`,
              },
              avatar: {
                image: message.author.displayAvatarURL({ format: "png" }),//message.member.displayAvatarURL({ format: "png" }),
              },
            });
        
            message.channel.send({ files: [image] });
        }
})
```

**Comment by DragonCat4012** [comment]
https://stackoverflow.com/questions/20660036/node-js-canvas-image-given-has-not-completed-loading

**Comment by DragonCat4012** [comment]
Error: Failed to load image Error: EINVAL, Invalid argument 'RIFF'
    at img.onerror (C:\Users\Kiara\Documents\Github\TestBot\index.js:28:37)
    at setSource (C:\Users\Kiara\Documents\Github\TestBot\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\Kiara\Documents\Github\TestBot\node_modules\canvas\lib\image.js:65:9)
    at Request._callback (C:\Users\Kiara\Documents\Github\TestBot\index.js:35:17)
    at Request.self.callback (C:\Users\Kiara\Documents\Github\TestBot\node_modules\request\request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (C:\Users\Kiara\Documents\Github\TestBot\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (C:\Users\Kiara\Documents\Github\TestBot\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:251:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)

**Comment by A-K-O-R-A** [comment]
The syntax of `displayAvatarURL({ format: "png" })` was changed to `displayAvatarURL({ extension: "png" })`. This issue is resolved as of Commit [d59e65a](https://github.com/AKORA-Studios/DiscordWelcomeCard/commit/d59e65ab22b2ee79045684ccd1497a36aeae8c3e) and [v4.9.0](https://www.npmjs.com/package/discord-welcome-card/v/4.9.0)
